-- ─────────────────────────────────────────────────────────────────────────────
-- Module 11 — Nature pilot indicator catalog seed
--
-- Source: Data Sourcing Layer v1, Section 4.1 (Nature, v3 elemental
-- structure). 33 indicators across the five elements: Earth, Air, Water,
-- Flora, Fauna. Five marked is_headline=true per the brief: one per element,
-- chosen as the indicator most directly reflecting the Horizon Goal.
--
-- Idempotent on (domain_id, name, source_name).
--
-- Tagged principles map to Module 1.5's four cross-domain principles:
--   indigenous-relational, substrate-health, not-knowing-stance,
--   legacy-temporal-dimension
-- ─────────────────────────────────────────────────────────────────────────────

begin;

-- Helper macro emulation: we just write each row explicitly. Boring is
-- correct here. Auditable is the priority.

insert into nextus_domain_indicators (
  domain_id, subdomain_slug, lens_slugs, name, unit, tier,
  source_name, source_url, endpoint_url,
  native_resolution, refresh_cadence, direction_preferred,
  methodology_note, status, structure_version, tagged_principles,
  is_headline, headline_order
) values

-- ─── Earth ───────────────────────────────────────────────────────────────────

(
  'nature', 'earth',
  array['climate', 'conservation-regeneration']::text[],
  'Soil organic carbon',
  'g/kg',
  'api',
  'ISRIC — World Soil Information',
  'https://www.isric.org/explore/soilgrids',
  'https://rest.isric.org/soilgrids/v2.0/properties/query',
  'local',
  'monthly',
  'up',
  'Soil organic carbon stocks at 0–30cm depth, modelled from global soil profile data. Higher values indicate healthier soil substrate and greater carbon storage capacity.',
  'active', 'v3',
  array['substrate-health', 'indigenous-relational']::text[],
  false, null
),
(
  'nature', 'earth',
  array['human-use-stewardship', 'conservation-regeneration']::text[],
  'Land degradation',
  '% land degraded',
  'scrape',
  'FAO WOCAT / SDG 15.3.1',
  'https://data.apps.fao.org/catalog/dataset/sdg-15-3-1',
  'https://data.apps.fao.org/catalog/dataset/sdg-15-3-1',
  'regional',
  'annual',
  'down',
  'Proportion of land that is degraded over total land area, per SDG indicator 15.3.1. Lower values indicate healthier land use patterns.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'earth',
  array['conservation-regeneration']::text[],
  'Protected land area',
  '% land protected',
  'api',
  'UNEP-WCMC — Protected Planet',
  'https://www.protectedplanet.net/',
  'https://api.protectedplanet.net/v3/protected_areas',
  'planetary',
  'monthly',
  'up',
  'Share of terrestrial area under formal protection. Counts national parks, reserves, and protected landscapes registered with UNEP-WCMC.',
  'active', 'v3',
  array['substrate-health', 'legacy-temporal-dimension']::text[],
  true, 1
),
(
  'nature', 'earth',
  array['indigenous-relational-knowledge', 'conservation-regeneration']::text[],
  'Indigenous and community land',
  '% land',
  'api',
  'LandMark Global Platform',
  'https://www.landmarkmap.org/',
  'https://www.landmarkmap.org/api/v1/indigenous-lands',
  'regional',
  'monthly',
  'up',
  'Share of land formally recognised as indigenous or community-held. The platform surfaces this through the LandMark partnership and treats indigenous stewardship as a Conservation lens.',
  'active', 'v3',
  array['indigenous-relational', 'legacy-temporal-dimension']::text[],
  false, null
),
(
  'nature', 'earth',
  array['climate']::text[],
  'Earthquake activity',
  'M4.5+ events / month',
  'api',
  'USGS Earthquake Hazards',
  'https://earthquake.usgs.gov/',
  'https://earthquake.usgs.gov/fdsnws/event/1/query',
  'planetary',
  'daily',
  'context',
  'Count of magnitude 4.5 or greater seismic events globally in the past 30 days. Context indicator: tectonic activity is not directly amenable to human action but provides geological context.',
  'active', 'v3',
  array['not-knowing-stance']::text[],
  false, null
),
(
  'nature', 'earth',
  array['pollution-waste', 'human-use-stewardship']::text[],
  'Mining footprint',
  'index',
  'scrape',
  'Global Mining Atlas (WRI)',
  'https://www.globalforestwatch.org/',
  'https://www.globalforestwatch.org/map',
  'regional',
  'annual',
  'down',
  'Composite index of land area under active mining operations, from World Resources Institute overlays. Lower values indicate less extractive pressure on the substrate.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),

-- ─── Air ─────────────────────────────────────────────────────────────────────

(
  'nature', 'air',
  array['climate']::text[],
  'Atmospheric CO₂ concentration',
  'ppm',
  'api',
  'NOAA Global Monitoring Laboratory',
  'https://gml.noaa.gov/ccgg/trends/',
  'https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_mm_mlo.txt',
  'planetary',
  'daily',
  'down',
  'Monthly mean atmospheric CO₂ concentration measured at Mauna Loa Observatory, Hawaii. The longest continuous record of atmospheric CO₂. Lower is better for climate stability.',
  'active', 'v3',
  array['substrate-health', 'legacy-temporal-dimension']::text[],
  true, 2
),
(
  'nature', 'air',
  array['climate']::text[],
  'Methane concentration',
  'ppb',
  'api',
  'NOAA Global Monitoring Laboratory',
  'https://gml.noaa.gov/ccgg/trends_ch4/',
  'https://gml.noaa.gov/webdata/ccgg/trends/ch4/ch4_mm_gl.txt',
  'planetary',
  'weekly',
  'down',
  'Globally averaged atmospheric methane concentration, parts per billion. Methane is the second largest contributor to anthropogenic warming.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'air',
  array['climate']::text[],
  'Global mean temperature',
  '°C anomaly',
  'api',
  'NASA GISS Surface Temperature',
  'https://data.giss.nasa.gov/gistemp/',
  'https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.txt',
  'planetary',
  'monthly',
  'down',
  'Monthly land–ocean temperature anomaly versus the 1951–1980 baseline. Lower anomaly is closer to pre-industrial baseline.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'air',
  array['pollution-waste', 'human-use-stewardship']::text[],
  'Local air quality (PM2.5)',
  'µg/m³',
  'api',
  'OpenAQ',
  'https://openaq.org/',
  'https://api.openaq.org/v3/locations',
  'local',
  'daily',
  'down',
  'Particulate matter 2.5 micrometer concentration aggregated from station-level OpenAQ readings. WHO guideline annual mean is 5 µg/m³.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'air',
  array['climate', 'human-use-stewardship']::text[],
  'National emissions',
  'Mt CO₂e / year',
  'api',
  'Climate TRACE',
  'https://climatetrace.org/',
  'https://api.climatetrace.org/v6/country/emissions',
  'regional',
  'monthly',
  'down',
  'National greenhouse gas emissions from satellite and ground monitoring, broken down by sector. More granular than self-reported inventories.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'air',
  array['conservation-regeneration', 'climate']::text[],
  'Ozone layer state',
  'Dobson units',
  'scrape',
  'NASA OzoneWatch',
  'https://ozonewatch.gsfc.nasa.gov/',
  'https://ozonewatch.gsfc.nasa.gov/meteorology/',
  'planetary',
  'daily',
  'up',
  'Total column ozone in Dobson units, with attention to the Antarctic ozone hole. The rare good-news climate story: recovery underway since the Montreal Protocol.',
  'active', 'v3',
  array['substrate-health', 'legacy-temporal-dimension']::text[],
  false, null
),
(
  'nature', 'air',
  array['climate']::text[],
  'Weather extremes index',
  'index',
  'scrape',
  'NOAA Climate Extremes Index',
  'https://www.ncei.noaa.gov/access/monitoring/cei/',
  'https://www.ncei.noaa.gov/access/monitoring/cei/',
  'regional',
  'monthly',
  'down',
  'Composite index measuring the share of land area experiencing extreme conditions. Higher values indicate more disrupted weather patterns.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),

-- ─── Water ───────────────────────────────────────────────────────────────────

(
  'nature', 'water',
  array['human-use-stewardship']::text[],
  'Freshwater stress (Aqueduct)',
  'index 0-5',
  'api',
  'WRI Aqueduct Water Risk',
  'https://www.wri.org/aqueduct',
  'https://www.wri.org/aqueduct',
  'regional',
  'monthly',
  'down',
  'Ratio of total water withdrawals to available renewable surface and groundwater supplies. Higher values indicate greater water stress.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'water',
  array['human-use-stewardship']::text[],
  'Renewable water resources',
  'm³ per capita',
  'scrape',
  'FAO AQUASTAT',
  'https://data.apps.fao.org/aquastat/',
  'https://data.apps.fao.org/aquastat/?lang=en',
  'regional',
  'annual',
  'up',
  'Total renewable freshwater resources per capita. The denominator changes with population; the numerator changes with the hydrological system.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'water',
  array['climate']::text[],
  'Sea surface temperature',
  '°C anomaly',
  'api',
  'NOAA Coral Reef Watch',
  'https://coralreefwatch.noaa.gov/',
  'https://coralreefwatch.noaa.gov/product/5km/',
  'planetary',
  'daily',
  'down',
  'Sea surface temperature anomaly versus a long-term climatology. Sustained positive anomalies drive marine heatwaves and coral bleaching.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'water',
  array['conservation-regeneration', 'human-use-stewardship']::text[],
  'Ocean Health Index',
  'index 0-100',
  'scrape',
  'Ocean Health Index (UC Santa Barbara)',
  'https://oceanhealthindex.org/',
  'https://oceanhealthindex.org/scores/',
  'regional',
  'annual',
  'up',
  'Composite index across ten goals: food provision, biodiversity, clean waters, sense of place, livelihoods, and more. Higher is better.',
  'active', 'v3',
  array['substrate-health', 'indigenous-relational']::text[],
  true, 3
),
(
  'nature', 'water',
  array['climate']::text[],
  'Arctic sea ice extent',
  'million km²',
  'api',
  'NSIDC Sea Ice Index',
  'https://nsidc.org/arcticseaicenews/',
  'https://nsidc.org/arcticseaicenews/sea-ice-tools/',
  'planetary',
  'daily',
  'up',
  'Daily Arctic sea ice extent, the area of ocean with at least 15% ice cover. The September minimum is the standard climate-bellwether reading.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'water',
  array['conservation-regeneration']::text[],
  'River basin health',
  'index',
  'scrape',
  'WWF Global Wetlands & River Atlas',
  'https://www.worldwildlife.org/',
  'https://www.worldwildlife.org/publications',
  'regional',
  'annual',
  'up',
  'Composite of biological condition, hydrological alteration, and connectivity across the world''s major river basins.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'water',
  array['conservation-regeneration']::text[],
  'Marine protected area',
  '% ocean',
  'api',
  'UNEP-WCMC — Protected Planet',
  'https://www.protectedplanet.net/',
  'https://api.protectedplanet.net/v3/protected_areas?marine=true',
  'planetary',
  'monthly',
  'up',
  'Share of ocean under formal protection. Rising toward the 30-by-30 target adopted by the UN High Seas Treaty.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),

-- ─── Flora ───────────────────────────────────────────────────────────────────

(
  'nature', 'flora',
  array['climate', 'human-use-stewardship']::text[],
  'Tree cover loss',
  'Mha lost / year',
  'api',
  'Global Forest Watch (Hansen / UMD)',
  'https://www.globalforestwatch.org/',
  'https://data-api.globalforestwatch.org/dataset/umd_tree_cover_loss/latest',
  'planetary',
  'weekly',
  'down',
  'Annual loss of tree-covered area, measured by satellite at 30m resolution. Loss is gross — does not account for regrowth.',
  'active', 'v3',
  array['substrate-health', 'legacy-temporal-dimension']::text[],
  true, 4
),
(
  'nature', 'flora',
  array['conservation-regeneration', 'climate']::text[],
  'Primary forest loss',
  'Mha lost / year',
  'api',
  'Global Forest Watch',
  'https://www.globalforestwatch.org/',
  'https://data-api.globalforestwatch.org/dataset/umd_primary_forest/latest',
  'planetary',
  'annual',
  'down',
  'Loss of primary tropical forests specifically — the most carbon-dense and biodiverse forest type. A small subset of total tree cover loss but the most ecologically consequential.',
  'active', 'v3',
  array['substrate-health', 'legacy-temporal-dimension']::text[],
  false, null
),
(
  'nature', 'flora',
  array['climate', 'human-use-stewardship']::text[],
  'Active wildfires',
  'fires (last 24h)',
  'api',
  'NASA FIRMS',
  'https://firms.modaps.eosdis.nasa.gov/',
  'https://firms.modaps.eosdis.nasa.gov/api/country/',
  'planetary',
  'daily',
  'down',
  'Active fire detections in the past 24 hours from MODIS and VIIRS satellite sensors. Fast-moving climate signal during fire season.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'flora',
  array['conservation-regeneration']::text[],
  'Tree cover gain',
  'Mha gained',
  'api',
  'Global Forest Watch',
  'https://www.globalforestwatch.org/',
  'https://data-api.globalforestwatch.org/dataset/umd_tree_cover_gain/latest',
  'regional',
  'annual',
  'up',
  'Gross tree cover gain over the most recent 20-year window. Includes plantation expansion as well as natural regrowth.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'flora',
  array['conservation-regeneration']::text[],
  'Plant species threatened',
  'species',
  'api',
  'IUCN Red List',
  'https://www.iucnredlist.org/',
  'https://apiv3.iucnredlist.org/api/v3/country/getspecies/',
  'planetary',
  'monthly',
  'down',
  'Count of plant species classified as Vulnerable, Endangered, or Critically Endangered on the IUCN Red List.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'flora',
  array['conservation-regeneration', 'human-use-stewardship']::text[],
  'Crop diversity (accessions)',
  'accessions',
  'api',
  'Crop Trust / Genesys',
  'https://www.genesys-pgr.org/',
  'https://api.genesys-pgr.org/api/v1/acn/',
  'planetary',
  'monthly',
  'up',
  'Genebank accessions stored globally. Each accession is a distinct seed sample preserving genetic variability.',
  'active', 'v3',
  array['substrate-health', 'legacy-temporal-dimension']::text[],
  false, null
),
(
  'nature', 'flora',
  array['conservation-regeneration', 'climate']::text[],
  'Mangrove extent',
  'km²',
  'api',
  'Global Mangrove Watch',
  'https://www.globalmangrovewatch.org/',
  'https://www.globalmangrovewatch.org/',
  'regional',
  'annual',
  'up',
  'Total mangrove forest extent globally. Mangroves are simultaneously Flora, Water, and Climate-lensed.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),

-- ─── Fauna ───────────────────────────────────────────────────────────────────

(
  'nature', 'fauna',
  array['conservation-regeneration']::text[],
  'Living Planet Index',
  'index (1970=100)',
  'scrape',
  'WWF / ZSL Living Planet Report',
  'https://livingplanetindex.org/',
  'https://livingplanetindex.org/data_portal',
  'planetary',
  'annual',
  'up',
  'Average change in population sizes of vertebrate species since 1970. Latest value indicates the average population is roughly one-third its 1970 level.',
  'active', 'v3',
  array['substrate-health', 'legacy-temporal-dimension']::text[],
  true, 5
),
(
  'nature', 'fauna',
  array['conservation-regeneration']::text[],
  'Species threatened (all)',
  'species',
  'api',
  'IUCN Red List',
  'https://www.iucnredlist.org/',
  'https://apiv3.iucnredlist.org/api/v3/country/getspecies/',
  'planetary',
  'monthly',
  'down',
  'All animal species on the IUCN Red List in Vulnerable, Endangered, or Critically Endangered categories.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'fauna',
  array['conservation-regeneration']::text[],
  'Biodiversity Intactness Index',
  'index 0-100',
  'scrape',
  'Natural History Museum UK',
  'https://www.nhm.ac.uk/our-science/services-and-resources/data/biodiversity-indicators.html',
  'https://www.nhm.ac.uk/our-science/services-and-resources/data/biodiversity-indicators.html',
  'regional',
  'annual',
  'up',
  'Estimated proportion of original species abundance remaining at a location. Below 90 indicates ecological compromise; below 30 indicates severe loss.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'fauna',
  array['human-use-stewardship']::text[],
  'Fish stock status',
  '% sustainable',
  'scrape',
  'RAM Legacy Stock Assessment Database',
  'https://www.ramlegacy.org/',
  'https://www.ramlegacy.org/',
  'regional',
  'annual',
  'up',
  'Share of assessed fish stocks at biologically sustainable levels. Tracks the trajectory of marine fishery management.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'fauna',
  array['conservation-regeneration', 'climate']::text[],
  'Pollinator populations',
  'index',
  'scrape',
  'IPBES Global Pollinator Assessment',
  'https://ipbes.net/',
  'https://ipbes.net/assessment-reports/pollinators',
  'regional',
  'annual',
  'up',
  'Composite indicator of wild pollinator population trends from the IPBES global assessment.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'fauna',
  array['human-use-stewardship']::text[],
  'Wildlife trade (CITES)',
  'transactions',
  'scrape',
  'CITES Trade Database',
  'https://trade.cites.org/',
  'https://trade.cites.org/cites_trade/',
  'regional',
  'monthly',
  'down',
  'Number of CITES-recorded wildlife trade transactions. Higher counts indicate greater extraction pressure on listed species.',
  'active', 'v3',
  array['substrate-health']::text[],
  false, null
),
(
  'nature', 'fauna',
  array['human-use-stewardship']::text[],
  'Livestock / domesticated animals',
  'count (millions)',
  'api',
  'FAOSTAT',
  'https://www.fao.org/faostat/',
  'https://fenixservices.fao.org/faostat/api/v1/en/data/QCL',
  'regional',
  'annual',
  'context',
  'Global counts of major domesticated species. Context indicator: rising counts reflect food demand but also habitat conversion and emissions.',
  'active', 'v3',
  array['not-knowing-stance']::text[],
  false, null
)

on conflict (domain_id, name, source_name) do update
set
  subdomain_slug      = excluded.subdomain_slug,
  lens_slugs          = excluded.lens_slugs,
  unit                = excluded.unit,
  tier                = excluded.tier,
  source_url          = excluded.source_url,
  endpoint_url        = excluded.endpoint_url,
  native_resolution   = excluded.native_resolution,
  refresh_cadence     = excluded.refresh_cadence,
  direction_preferred = excluded.direction_preferred,
  methodology_note    = excluded.methodology_note,
  status              = excluded.status,
  structure_version   = excluded.structure_version,
  tagged_principles   = excluded.tagged_principles,
  is_headline         = excluded.is_headline,
  headline_order      = excluded.headline_order,
  updated_at          = now();

commit;
