// ─────────────────────────────────────────────────────────────
// horizonDecompositions.js
//
// Per-domain decomposition of each civilisational Horizon Goal —
// unpacks what the qualitative goal actually means, names the
// indicators we use and why, acknowledges what we are not
// measuring. Surfaced in CivDomainPanel when a domain is
// featured.
//
// Source: NextUs_Civilisational_Horizons_v1.md (living architecture
// document). Keep this file in sync with the canonical doc; the
// doc is authoritative.
// ─────────────────────────────────────────────────────────────

export const HORIZON_DECOMPOSITIONS = {
  "nature": {
    "goal": "Ecosystems are thriving and we are living in harmony with the planet.",
    "unpacking": "A planet whose living systems are intact, regenerating, and capable of supporting all the life that depends on them — including human life, but not only. The atmosphere holds a climate within the range Earth's biosphere evolved in. The oceans are productive, not acidifying past the point of recovery. Forests are growing, not shrinking. The other species we share the planet with are present in numbers and varieties roughly comparable to what existed before industrial civilisation. And the human relationship with all of this is one of participation rather than extraction — we are part of the system, taking what we need at rates the system can replenish.\n\nThe goal does not require returning to a pre-industrial state. It requires a present in which the trajectory has reversed.",
    "how_we_measure": "Five indicators, each a window into a different aspect of the whole:\n\n**Atmospheric CO₂ concentration** is the single clearest signal of how far we have pushed the climate system out of its evolved range. We set the target at 280 ppm — the pre-industrial baseline that the rest of the biosphere is calibrated to — and the floor at 450 ppm, the point past which most climate models forecast irreversible cascading change. We are currently at 427 ppm. The gap is real and measured in the only currency the atmosphere recognises: molecules of carbon.\n\n**Protected land area** measures how much of Earth's terrestrial surface is under formal conservation status. The Convention on Biological Diversity's 30x30 framework — 30% of land protected by 2030 — sets the target. We are at 17.1%, roughly halfway.\n\n**Ocean Health Index** is a composite score from the Ocean Health Index project assessing food provision, biodiversity, carbon storage, coastal livelihoods, clean waters, and tourism across the world's oceans. We use the global score directly; the target is 100 (all sub-indices fully met) and the floor is 40.\n\n**Tree cover loss** tracks how many millions of hectares of forest the planet lost in the most recent measurement year, drawn from Global Forest Watch. Lower is better. We set the target at 1 Mha/year (near-zero net deforestation) and the floor at 15 Mha/year.\n\n**Living Planet Index** is the WWF/ZSL composite tracking abundance of monitored vertebrate populations since 1970. A score of 100 means populations are at 1970 levels; we are at 73, meaning monitored populations have declined by about 27% in fifty years.",
    "not_measuring": "Soil health. Microbial biodiversity. Pollinator populations. Freshwater ecosystem function. Indigenous land stewardship as a distinct practice rather than a generic conservation category. These are gaps in our current indicator set — not because they don't matter, but because we have not yet found data sources global in scope, methodologically clean enough to score, and updated frequently enough to track. They are open invitations for contribution.",
    "where_now": "Nature scores low — the climate signal in particular is severe. But the picture is not uniform. Protected land is approaching the 30x30 target faster than expected. The growth of renewable energy has bent the curve on emissions without yet reversing it. The number of actors working in this domain is growing faster than in any other. The gap is large; the leverage is real."
  },
  "human-being": {
    "goal": "Every person has what they need to know themselves, develop fully, and bring what they came here to bring.",
    "unpacking": "A world in which the conditions for human flourishing are present at scale — material, developmental, and inner. People live long enough to do what they are here to do. Children survive their first five years almost everywhere. Clean water reaches every home. Literacy is universal. The mental and emotional conditions for development are supported, not actively eroded. People are physically safe in their daily lives. And the inner dimensions of being human — meaning, dignity, the capacity to know oneself — are present, not just absent of crisis.\n\nThe goal does not promise equal outcomes. It promises the conditions under which the question \"what am I here for\" becomes a real one for everyone.",
    "how_we_measure": "Six indicators spanning the basic material conditions of life through to its inner dimensions:\n\n**Life expectancy at birth** is the single most-cited proxy for whether a population's basic needs are being met. Target: 85 years (the high end of currently achieved national averages). Floor: 50 years. We are at 73.3 globally.\n\n**Under-5 mortality rate** measures deaths per 1,000 live births before age five — the most sensitive indicator of whether the medical, nutritional, and developmental conditions of early life are in place. Target: 2.5 (a near-floor achievable with current medical knowledge). Floor: 80. We are at 36.4.\n\n**Access to basic drinking water** is the percentage of population with access to a safely managed water source. Target: 100%. Floor: 50%. We are at 73%.\n\n**Adult literacy rate** is the percentage of people aged 15+ able to read and write. The strongest single predictor of agency in modern life. Target: 100%. Floor: 50%. We are at 87%.\n\n**Cantril life satisfaction ladder** is the World Happiness Report's primary measure — respondents place themselves on a 0–10 ladder of overall life satisfaction. Target: 8 (the level achieved by the highest-scoring nations). Floor: 3. The global mean is 5.5.\n\n**Intentional homicide rate** measures the most extreme form of physical insecurity in daily life. Target: 1 per 100,000 (the rate achieved by the safest nations). Floor: 20 per 100,000. We are at 5.8 globally.",
    "not_measuring": "The inner development dimensions. Meaning. Mental health prevalence in a globally comparable way. Loneliness and social isolation at scale. The capacity for self-knowledge, which has no widely-used quantitative proxy at all. These absences are why the Inner Game domain exists on the personal side — but on the planetary side, the data has not yet been assembled at this scale. We name the gap rather than pretending it isn't there.",
    "where_now": "Human Being scores stronger than most other domains — the long arc of medical, educational, and material progress is real and continues. But the inner dimensions are unmeasured, the disparities within the global average are vast, and the slowing rate of progress in some indicators (life expectancy in particular has plateaued or reversed in several wealthy nations) suggests the easy gains have been made."
  },
  "society": {
    "goal": "Humanity knows how to be human together — and every individual is better for it.",
    "unpacking": "A world in which the structures humans build to live alongside each other actually work — for the people inside them. Democratic institutions that are responsive, trusted, and stable. A press that is free enough to hold power accountable. Levels of inter-personal trust that make cooperation possible. The absence of mass violence as a way of resolving disputes. Migration that happens by choice, not flight. A social fabric strong enough to hold the disagreements that come with being human together.\n\nThe goal does not specify a particular political arrangement. It specifies the conditions under which any arrangement can serve the people inside it.",
    "how_we_measure": "Five indicators spanning governance, peace, and the trust fabric that holds the rest together:\n\n**Liberal democracy index** is V-Dem's composite measure of free and fair elections, civil liberties, executive accountability, and rule of law across all nations. Target: 0.7 (the level achieved by stable democracies). Floor: 0.2. The global mean is 0.40 and falling.\n\n**Refugees by country of origin** counts the total number of people displaced across international borders by persecution or violence. A measure of how many places have become impossible to stay in. Target: 10 million (an unavoidable baseline in a world with some conflict). Floor: 50 million. We are at 43.7 million — a record high.\n\n**Battle-related deaths** tracks annual deaths in active armed conflicts. Target: 20,000/year (the level of the relatively peaceful 2010s). Floor: 200,000/year. We are at 162,000 — driven by Ukraine, Sudan, and Gaza.\n\n**World Press Freedom Index** is Reporters Without Borders' composite score for the freedom journalists have to report. The 2025 global average score is 55, the lowest since the index began.\n\n**Generalised social trust** is the percentage of survey respondents who say \"most people can be trusted,\" from the World Values Survey and Gallup. The single most robust predictor of whether collective action is possible. Target: 70%. Floor: 10%. The global mean is around 30%.",
    "not_measuring": "Civic participation rates. Local governance quality. The strength of civil society organisations at the community scale. The lived experience of belonging or its absence. The measures we use are all national-level. The texture of social life happens below that. We name the gap.",
    "where_now": "Society scores low. Democracy is in retreat across multiple regions. Refugees are at record highs. Battle deaths are climbing. Press freedom is at its lowest measured level. Social trust has not recovered from its long-term decline. The fabric is fraying — measurably."
  },
  "technology": {
    "goal": "Our creations support and amplify life.",
    "unpacking": "A world in which the tools humans build serve the people who use them and the planet they live on. Universal access to the infrastructure of modern life — electricity, the internet — not as a luxury but as a baseline. Energy generation that does not destroy the climate that makes life possible. Computational systems that are accountable to human values. The waste products of our technology cycled back into use, not piled up.\n\nThe goal does not require slowing down. It requires building wisely.",
    "how_we_measure": "Five indicators spanning access, sustainability, and accountability:\n\n**Internet penetration** is the percentage of the global population with access to the internet — the primary infrastructure of contemporary life. Target: 100%. Floor: 50%. We are at 68%.\n\n**Access to electricity** is the percentage of the global population with access to electrical power. Target: 100%. Floor: 70%. We are at 92%.\n\n**AI incidents recorded** counts publicly documented harms attributed to AI systems annually, from the AI Incident Database and AIAAIC repository. A proxy for whether AI capability is outpacing its accountability. Target: 100/year (some incidents are unavoidable in any deployed technology). Floor: 2000/year. We are at 798.\n\n**Global e-waste generation per capita** measures kilograms of electronic waste produced per person per year. The trailing edge of accelerating device cycles. Target: 3 kg/person/year. Floor: 15. We are at 7.8.\n\n**Renewable share of electricity generation** is the percentage of global electricity from renewable sources. The single most leveraged technology shift for the climate. Target: 80%. Floor: 15%. We are at 30%.",
    "not_measuring": "Open-source software adoption and the commons of shared digital infrastructure. The biological technologies that work with life rather than override it. Automation's effect on meaningful work. The energy intensity of computation itself. The texture of how technology is governed at the level of specific platforms and protocols. Gaps we name.",
    "where_now": "Technology is one of the higher-scoring domains. Electricity access has improved dramatically. Renewable energy has scaled faster than most models predicted. But AI capability is arriving faster than the governance frameworks needed to hold it, e-waste keeps climbing, and 2.4 billion people still aren't online. The gap between technological capability and our collective wisdom in using it is the defining tension of this domain."
  },
  "finance-economy": {
    "goal": "Resources flow toward what sustains and generates life — rewarding care, contribution, and long-term thinking.",
    "unpacking": "A world in which economic activity serves life. People are not living in extreme poverty. Inequality is contained within levels that don't tear societies apart. Work is available for those who want it. The capital required to meet existential challenges — climate adaptation in particular — is flowing where it's needed. And the materials we use are increasingly cycled back through the economy rather than discarded.\n\nThe goal does not specify a particular economic system. It specifies what an economy is *for*.",
    "how_we_measure": "Five indicators spanning poverty, inequality, employment, climate finance, and materials:\n\n**Extreme poverty headcount** is the percentage of the global population living below the World Bank's $2.15/day extreme poverty line. The most basic measure of whether the economy is delivering survival. Target: 0%. Floor: 40%. We are at 10.4%.\n\n**Gini index (population-weighted mean)** is the World Bank's composite measure of income inequality across all nations, weighted by population. Target: 25 (low inequality, comparable to Scandinavia). Floor: 70 (extreme inequality, comparable to the most unequal nations). We are at 38.0.\n\n**Unemployment rate (modeled ILO)** is the International Labour Organization's modeled global unemployment rate. Target: 3% (full employment with some frictional). Floor: 15%. We are at 4.9%.\n\n**Climate finance to developing economies** measures the annual flow of climate-related finance from developed to developing nations, in USD billions. The single most consequential expression of whether the world is treating climate as a shared problem. Target: $300bn/year (the level pledged at COP). Floor: $50bn. We are at $89.6bn — well short.\n\n**Global circularity rate** is the percentage of materials cycled back through the economy rather than extracted fresh, from Circle Economy's Global Circularity Report. Target: 20%. Floor: 5%. We are at 7.2%.",
    "not_measuring": "The care economy. Unpaid labour. Wealth concentration at the top. The flow of capital toward extraction versus regeneration. Impact investment scale. Whether GDP itself is the right top-level proxy for economic health. Gaps we name openly — and which the Wellbeing Economy Alliance, the Genuine Progress Indicator, and similar projects exist to address.",
    "where_now": "Economy scores in the middle. Poverty and unemployment are mid-range. Inequality is high but not catastrophic. Climate finance is well below pledged levels. The circular economy is barely beginning. The system continues to reward extraction over regeneration — measurably."
  },
  "legacy": {
    "goal": "We are ancestors worth having.",
    "unpacking": "A world in which the things humans before us built — cultural, linguistic, ecological, institutional — survive into the next generations. Languages don't disappear. World heritage isn't lost to neglect or violence. Indigenous communities have legal recognition of the lands their ancestors stewarded. Other species continue to exist alongside us. The oral traditions that carry knowledge older than any written record are passed forward rather than lost.\n\nThe goal does not romanticise the past. It asks whether what we have inherited will survive us.",
    "how_we_measure": "Four scoreable indicators plus one qualitative one we name explicitly:\n\n**World Heritage Sites in Danger** counts the number of UNESCO World Heritage Sites currently on the list of those in danger — from conflict, neglect, or environmental damage. Target: 10 (an unavoidable baseline in a turbulent world). Floor: 80. We are at 56.\n\n**Endangered languages** counts the number of human languages classified as endangered or critically endangered by UNESCO. Target: 1,500 (acknowledging some loss is inevitable in a globalising world). Floor: 3,500. We are at approximately 3,045.\n\n**Indigenous and community land recognised** measures millions of hectares of land with formal legal recognition of indigenous or community tenure, from the Rights and Resources Initiative. Target: 2,000 Mha. Floor: 500 Mha. We are at 1,100 Mha.\n\n**Species extinctions documented** counts the cumulative number of species documented as having gone extinct since 1500, from the IUCN Red List. Target: 900 (close to the current count — meaning the goal is essentially \"no more from here\"). Floor: 2,000. We are at approximately 1,000.\n\n**Vitality of oral tradition** is qualitative. We have no global quantitative index. UNESCO maintains the Intangible Cultural Heritage list with 730 elements in 2024, but transmission rates — whether the next generation actually receives what the elders carry — are not centrally measured. We name the gap.",
    "not_measuring": "The vitality of ritual, ceremony, and seasonal practice. Apprenticeship rates in traditional skills. Whether intergenerational transmission of knowledge is happening in living households. The fate of cultural memory in digital form. The institutional voice (or absence of voice) of future generations.",
    "where_now": "Legacy is structurally difficult to score because so much of what matters in this domain is qualitative. The numerical indicators tell us heritage sites are at risk, languages are disappearing faster than they are being preserved, and indigenous land tenure is advancing slowly. The qualitative dimensions — whether oral tradition is actually being transmitted — we cannot yet say."
  },
  "vision": {
    "goal": "Into the unknown. On purpose. Together.",
    "unpacking": "A world in which humanity has a shared sense of direction. Not unanimity — direction. The institutions and practices that allow collective foresight, long-range planning, and coordination across generations exist and are taken seriously. The risk of self-inflicted catastrophe is moving away from us, not toward us. The shared global goals that exist — the SDGs, the climate agreements, the future-generations commitments — are being met. Research and development is funded as if the future matters. And the cultural capacity for collective imagination — the ability to envision futures worth building — is alive rather than dormant.\n\nThe goal does not specify what humanity should be building toward. It specifies that we should be capable of choosing.",
    "how_we_measure": "Four scoreable indicators plus one qualitative:\n\n**Doomsday Clock — seconds to midnight** is the Bulletin of the Atomic Scientists' annual assessment of how close humanity stands to self-inflicted catastrophe, expressed in seconds before symbolic midnight. Target: 900 seconds (a relative safety distance, last achieved during the post-Cold War period). Floor: 30 seconds. As of January 2026, we are at 85 seconds — the closest the clock has ever been to midnight in its 79-year history.\n\n**Jurisdictions with future-generations institutions** counts the number of national, regional, or municipal jurisdictions that have established formal institutional representation for the rights or interests of future generations — Future Generations Commissioners, intergenerational equity offices, and similar bodies. Tracked by the All-Party Parliamentary Group for Future Generations. Target: 50. Floor: 5. We are at approximately 27.\n\n**SDG Index global score** is the Sustainable Development Solutions Network's composite measure of how the world is performing on the seventeen Sustainable Development Goals. The single best-known attempt to operationalise shared global aspiration. Target: 85. Floor: 50. The global average is 67.\n\n**R&D expenditure** measures global research and development spending as a percentage of GDP. A proxy for whether the world is investing in its own future. Target: 4%. Floor: 1%. We are at approximately 2.4%.\n\n**Vitality of collective imagination** is qualitative. We have no global index of whether humans can collectively envision futures worth building. Researchers note that fictional futures in popular culture have grown increasingly dystopian over recent decades. Futures literacy programmes are growing through the UNESCO network (78 member states as of 2024). We name the gap.",
    "not_measuring": "The number and reach of cross-domain coordination platforms. The presence or absence of shared civilisational goals at the level of culture rather than institutions. Whether public discourse is capable of holding long timeframes. The relationship between attention economics and our capacity for foresight.",
    "where_now": "Vision is the most under-resourced domain and the one whose absence creates a ceiling for all the others. The Doomsday Clock is the closest to midnight it has ever been. Future-generations institutions exist but in modest numbers. R&D investment is roughly half of what would put humanity on a trajectory of acceleration. And the collective capacity for imagining better futures — by every available proxy — is weakening rather than strengthening. This is the domain NextUs itself exists, in part, to address."
  }
}
