-- 180_pulse_events.sql — SUPERSEDED. DO NOT RUN.
--
-- This migration has moved to `184_pulse_events.sql`.
--
-- Why: three separate lines of work took the number 180 in parallel — the
-- Care Protocol, the NextSteps phase layer, and this one. The other two broke
-- their tie by both moving to 181, which left 181 contested as well: the
-- social half's `sparks` migration was already there. So both of this drop's
-- contested files have moved clear, 180 → 184 and 181 → 185. The two that
-- were never contested, 182_milestones and 183_moment_featured, keep their
-- numbers.
--
-- All four are order-independent of each other and of the Care / NextSteps
-- work — they touch entirely different tables — so nothing depends on which
-- ran first. If this file was already run as 180, run 184 as well: it is the
-- same content, and it is idempotent.
--
-- This file is left as a tombstone rather than deleted, because a
-- drag-and-drop merge cannot remove files. If it were simply dropped from the
-- delivery, the old copy would survive on disk and a later reader would find
-- two live migrations numbered 180 with no way to tell which was real.
--
-- Safe to delete whenever convenient, and equally safe to leave: the whole
-- file is comments, so running it does nothing at all.
