-- 180_care_protocol.sql — SUPERSEDED. DO NOT RUN.
--
-- This migration has moved to `181_care_protocol.sql`, which is a superset:
-- it carries every fix from the security review, including the token-scoped
-- RPC that replaces the unsafe anon read policy on care_shares.
--
-- The Care Protocol drop's own DELETE_ME_FIRST.txt asked for this file to be
-- deleted by hand before applying. It was still present in the tree, so it is
-- overwritten here with a tombstone instead — a drag-and-drop merge cannot
-- remove a file, and leaving it live meant a reader could run the pre-review
-- version by mistake. Same convention the NextSteps drop used at this number.
--
-- IF THIS FILE WAS ALREADY RUN in Supabase: run 181_care_protocol.sql as well.
-- It is idempotent and it additionally drops the old anon read policy, which
-- is what closes the hole described in docs/care-protocol.md §8.
--
-- Safe to delete whenever convenient. The whole file is comments, so running
-- it does nothing at all.
--
-- (Overwritten by the social-half review pass, 26 July 2026 — flagged rather
-- than done silently, since this file belongs to another drop.)
