-- 180_nextsteps_phases.sql — SUPERSEDED. DO NOT RUN.
--
-- This migration has moved to `181_nextsteps_phases.sql`.
--
-- Why: the Care Protocol work took the number 180 in parallel, so the repo
-- briefly had two migrations called 180. The NextSteps phase layer was
-- renumbered to 181 to break the tie. The two are order-independent, because
-- they touch entirely different tables, so nothing depends on which ran first.
--
-- This file is left in place as a tombstone rather than deleted, because a
-- drag-and-drop merge cannot remove files. If it were simply dropped from the
-- delivery, the old copy would survive on disk and a later reader would find
-- two migrations numbered 180 with no way to tell which was real. Overwriting
-- it with this note is the only way the merge itself can resolve the collision.
--
-- It is safe to delete this file whenever convenient, and equally safe to leave
-- it: the whole file is comments, so running it does nothing at all.
--
-- If you already ran the original 180_nextsteps_phases.sql against Supabase,
-- there is nothing to undo. 181 is the same migration plus the renumbering
-- note, and it is idempotent, so running it is a no-op over anything already
-- applied.
--
-- Run instead:  sql/181_nextsteps_phases.sql
