-- 181_care_protocol.sql — SUPERSEDED. DO NOT RUN.
--
-- This migration has moved to `187_care_protocol.sql`.
--
-- Why: `181` was picked to break the tie with the original `180_care_protocol`
-- collision, but in parallel it was also independently claimed by the
-- NextSteps phase layer (`181_nextsteps_phases.sql`) and by a new "sparks"
-- migration (`181_sparks.sql`). Three files cannot share one number, so Care
-- Protocol moved to `184`, then a further "pulse events" migration
-- independently claimed 184 too, so it moved once more to `187` — see the
-- tombstone left at `184_care_protocol.sql` for that leg of the story.
--
-- This file is left in place as a tombstone rather than deleted, for the same
-- reason `180_care_protocol.sql` and `180_nextsteps_phases.sql` were: a
-- drag-and-drop merge cannot remove files, so overwriting with a note is the
-- only way to mark a superseded copy rather than leave two files claiming the
-- same migration with no way to tell which is current.
--
-- It is safe to delete this file whenever convenient, and equally safe to
-- leave it: the whole file is comments, so running it does nothing at all.
--
-- If you already ran this exact file (181_care_protocol.sql, the fixed
-- version with the security-definer read function) against Supabase, there is
-- nothing to undo — 187 is identical content under the new number, and every
-- statement in it is idempotent.
--
-- Run instead:  sql/187_care_protocol.sql
