-- 181_sparks.sql — SUPERSEDED. DO NOT RUN.
--
-- This migration has moved to `185_sparks.sql`.
--
-- Why: 181 ended up claimed three times over — by the Care Protocol, by the
-- NextSteps phase layer (both of which moved here from 180 to break an
-- earlier tie), and by this. See the tombstone in 180_pulse_events.sql for
-- the full sequence.
--
-- Order-independent of both: `sparks` touches no table either of them does.
-- If this file was already run as 181, run 185 as well — same content,
-- idempotent.
--
-- Left as a tombstone rather than deleted: a drag-and-drop merge cannot
-- remove files, so overwriting is the only way the merge itself can resolve
-- the collision. Safe to delete whenever convenient. The whole file is
-- comments, so running it does nothing.
