-- 184_care_protocol.sql — SUPERSEDED. DO NOT RUN.
--
-- This migration has moved to `187_care_protocol.sql`.
--
-- Why: 184 was picked to break the tie left by the second 180/181 collision
-- (see the tombstones at 180 and 181), as the first number that looked free
-- across the whole sql/ directory at the time. In parallel, an unrelated
-- "pulse events" migration independently landed at the same number
-- (`184_pulse_events.sql`, itself renumbered from a 180 collision for the
-- same reason) — and `185_sparks.sql` / `186_social_half_fixes.sql` had also
-- since been claimed. Two files cannot share one number, so Care Protocol
-- moved once more, to 187, the first number genuinely free once all of that
-- is accounted for.
--
-- This file is left in place as a tombstone rather than deleted, for the same
-- reason `180_care_protocol.sql` and `181_care_protocol.sql` were: a
-- drag-and-drop merge cannot remove files, so overwriting with a note is the
-- only way to mark a superseded copy rather than leave two files claiming the
-- same migration with no way to tell which is current.
--
-- It is safe to delete this file whenever convenient, and equally safe to
-- leave it: the whole file is comments, so running it does nothing at all.
--
-- If you already ran this exact file (184_care_protocol.sql, the fixed
-- version with the security-definer read function) against Supabase, there is
-- nothing to undo — 187 is identical content under the new number, and every
-- statement in it is idempotent.
--
-- Run instead:  sql/187_care_protocol.sql
