-- ============================================================
-- NextUs Crisis Resources — Initial Seed
-- April 2026
--
-- Coverage:
--   US, Canada, UK, Australia: 3-5 resources each (deeper)
--   Other regions: 1 anchor each + international fallback
--
-- All numbers and URLs verified at seed time.
-- The integrity-cron will re-verify URLs weekly.
-- Phone numbers cannot be auto-verified — flagged for manual review.
-- ============================================================

INSERT INTO crisis_resources
  (country_code, region, name, phone, sms, web_url, hours, languages, types_supported, description, display_order)
VALUES

-- ── United States ─────────────────────────────────────────────
('US', NULL, '988 Suicide & Crisis Lifeline',
  '988', '988',
  'https://988lifeline.org',
  '24/7',
  ARRAY['English','Spanish','+250 via interpretation'],
  ARRAY['suicide','mental_health_crisis','substance_use','general_distress'],
  'Free, confidential support for anyone in emotional distress, mental health or substance crisis. Call, text, or chat 988. Press 1 for Veterans, 2 for Spanish, 4 for Native services.',
  10),

('US', NULL, 'Crisis Text Line',
  NULL, '741741',
  'https://www.crisistextline.org',
  '24/7',
  ARRAY['English','Spanish'],
  ARRAY['general_distress','mental_health_crisis','suicide'],
  'Text HOME to 741741 to connect with a trained crisis counselor. Free and confidential.',
  20),

('US', NULL, 'The Trevor Project (LGBTQ+ Youth)',
  '1-866-488-7386', '678678',
  'https://www.thetrevorproject.org',
  '24/7',
  ARRAY['English'],
  ARRAY['lgbtq','suicide','youth','mental_health_crisis'],
  'Crisis support specifically for LGBTQ+ young people under 25. Call, text START to 678-678, or chat online.',
  30),

('US', NULL, 'Trans Lifeline',
  '1-877-565-8860', NULL,
  'https://translifeline.org',
  '24/7',
  ARRAY['English','Spanish'],
  ARRAY['lgbtq','trans','mental_health_crisis','general_distress'],
  'Peer support hotline run by and for trans people. Confidential and not required to be in crisis to call.',
  40),

('US', NULL, 'SAMHSA National Helpline',
  '1-800-662-4357', NULL,
  'https://www.samhsa.gov/find-help/national-helpline',
  '24/7',
  ARRAY['English','Spanish'],
  ARRAY['substance_use','mental_health_treatment','referral'],
  'Treatment referral and information service for individuals and families facing mental health or substance use disorders.',
  50),

-- ── Canada ────────────────────────────────────────────────────
('CA', NULL, '9-8-8: Suicide Crisis Helpline',
  '988', '988',
  'https://988.ca',
  '24/7',
  ARRAY['English','French'],
  ARRAY['suicide','mental_health_crisis','general_distress'],
  'Canada''s national three-digit suicide crisis helpline. Bilingual, trauma-informed, culturally-appropriate support.',
  10),

('CA', NULL, 'Talk Suicide Canada',
  '1-833-456-4566', '45645',
  'https://talksuicide.ca',
  '24/7 phone, 4pm-midnight ET text',
  ARRAY['English','French'],
  ARRAY['suicide','mental_health_crisis'],
  'Toll-free national support. Text 45645 in the evenings.',
  20),

('CA', 'Quebec', 'Association québécoise de prévention du suicide',
  '1-866-277-3553', '1-855-957-5353',
  'https://www.aqps.info',
  '24/7',
  ARRAY['French'],
  ARRAY['suicide','mental_health_crisis'],
  '1-866-APPELLE. French-language suicide prevention support across Quebec.',
  30),

('CA', NULL, 'Kids Help Phone',
  '1-800-668-6868', '686868',
  'https://kidshelpphone.ca',
  '24/7',
  ARRAY['English','French'],
  ARRAY['youth','mental_health_crisis','general_distress'],
  'Counselling and information for children, teens, and young adults. Text CONNECT to 686868.',
  40),

-- ── United Kingdom ────────────────────────────────────────────
('GB', NULL, 'Samaritans',
  '116 123', NULL,
  'https://www.samaritans.org',
  '24/7',
  ARRAY['English'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Free, confidential, 24/7. Talk to a Samaritan about anything that''s troubling you. No judgement.',
  10),

('GB', NULL, 'Shout',
  NULL, '85258',
  'https://giveusashout.org',
  '24/7',
  ARRAY['English'],
  ARRAY['general_distress','mental_health_crisis','suicide'],
  'Text-based crisis support. Text SHOUT to 85258 to start a conversation with a trained volunteer.',
  20),

('GB', NULL, 'CALM (Campaign Against Living Miserably)',
  '0800 58 58 58', NULL,
  'https://www.thecalmzone.net',
  '5pm-midnight daily',
  ARRAY['English'],
  ARRAY['suicide','mental_health_crisis','general_distress'],
  'Support for anyone affected by suicide or suicidal thoughts. Webchat also available.',
  30),

('GB', NULL, 'SANEline',
  '0300 304 7000', NULL,
  'https://www.sane.org.uk',
  '4:30pm-10pm daily',
  ARRAY['English'],
  ARRAY['mental_health_crisis','general_distress'],
  'Specialist mental health support for anyone affected by mental illness, including family, friends, and carers.',
  40),

-- ── Australia ─────────────────────────────────────────────────
('AU', NULL, 'Lifeline Australia',
  '13 11 14', '0477 13 11 14',
  'https://www.lifeline.org.au',
  '24/7',
  ARRAY['English'],
  ARRAY['suicide','mental_health_crisis','general_distress'],
  'National crisis support and suicide prevention. Call, text, or chat online.',
  10),

('AU', NULL, 'Beyond Blue',
  '1300 22 4636', NULL,
  'https://www.beyondblue.org.au',
  '24/7',
  ARRAY['English'],
  ARRAY['mental_health_crisis','depression','anxiety','general_distress'],
  'Mental health support for depression, anxiety, and emotional wellbeing.',
  20),

('AU', NULL, 'Suicide Call Back Service',
  '1300 659 467', NULL,
  'https://www.suicidecallbackservice.org.au',
  '24/7',
  ARRAY['English'],
  ARRAY['suicide','mental_health_crisis'],
  'Free counselling for anyone affected by suicide. Phone, video, online chat.',
  30),

('AU', NULL, 'Kids Helpline',
  '1800 55 1800', NULL,
  'https://kidshelpline.com.au',
  '24/7',
  ARRAY['English'],
  ARRAY['youth','mental_health_crisis','general_distress'],
  'Counselling for young people aged 5 to 25. Phone, webchat, email.',
  40),

-- ── International / Anchor coverage for top regions ──────────
('IE', NULL, 'Samaritans Ireland',
  '116 123', NULL,
  'https://www.samaritans.org/ireland',
  '24/7',
  ARRAY['English'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Free, confidential 24/7 listening service across Ireland.',
  10),

('NZ', NULL, '1737 Need to Talk?',
  '1737', '1737',
  'https://1737.org.nz',
  '24/7',
  ARRAY['English'],
  ARRAY['general_distress','mental_health_crisis','suicide'],
  'Free call or text any time to talk with a trained counsellor.',
  10),

('NZ', NULL, 'Lifeline Aotearoa',
  '0800 543 354', '4357',
  'https://www.lifeline.org.nz',
  '24/7',
  ARRAY['English'],
  ARRAY['suicide','mental_health_crisis','general_distress'],
  'Free phone counselling and crisis support.',
  20),

('IN', NULL, 'iCall',
  '+91 9152987821', NULL,
  'https://icallhelpline.org',
  'Mon-Sat 8am-10pm IST',
  ARRAY['English','Hindi','+other Indian languages'],
  ARRAY['mental_health_crisis','general_distress'],
  'Free counselling service from the Tata Institute of Social Sciences.',
  10),

('IN', NULL, 'Vandrevala Foundation',
  '1860 2662 345', NULL,
  'https://www.vandrevalafoundation.com',
  '24/7',
  ARRAY['English','Hindi'],
  ARRAY['mental_health_crisis','suicide','general_distress'],
  'Free 24/7 mental health helpline.',
  20),

('ZA', NULL, 'SADAG (South African Depression and Anxiety Group)',
  '0800 567 567', NULL,
  'https://www.sadag.org',
  '24/7',
  ARRAY['English','Afrikaans','Zulu','Xhosa'],
  ARRAY['mental_health_crisis','suicide','depression','anxiety'],
  'Suicide Crisis Line. SMS 31393 for a callback.',
  10),

('ZA', NULL, 'Lifeline South Africa',
  '0861 322 322', NULL,
  'https://lifelinesa.co.za',
  '24/7',
  ARRAY['English'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Free counselling and crisis intervention.',
  20),

('DE', NULL, 'Telefonseelsorge',
  '0800 111 0 111', NULL,
  'https://www.telefonseelsorge.de',
  '24/7',
  ARRAY['German'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Free, anonymous, around-the-clock support across Germany.',
  10),

('FR', NULL, 'SOS Amitié',
  '09 72 39 40 50', NULL,
  'https://www.sos-amitie.com',
  '24/7',
  ARRAY['French'],
  ARRAY['general_distress','suicide'],
  'Free emotional support across France.',
  10),

('FR', NULL, '3114 (National Suicide Prevention)',
  '3114', NULL,
  'https://3114.fr',
  '24/7',
  ARRAY['French'],
  ARRAY['suicide','mental_health_crisis'],
  'France''s national suicide prevention number.',
  20),

('ES', NULL, 'Teléfono de la Esperanza',
  '717 003 717', NULL,
  'https://telefonodelaesperanza.org',
  '24/7',
  ARRAY['Spanish'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Free emotional support hotline across Spain.',
  10),

('IT', NULL, 'Telefono Amico',
  '02 2327 2327', NULL,
  'https://www.telefonoamico.it',
  '10am-12am daily',
  ARRAY['Italian'],
  ARRAY['general_distress','mental_health_crisis'],
  'Free anonymous emotional support across Italy.',
  10),

('NL', NULL, '113 Zelfmoordpreventie',
  '113', NULL,
  'https://www.113.nl',
  '24/7',
  ARRAY['Dutch'],
  ARRAY['suicide','mental_health_crisis'],
  'National suicide prevention helpline.',
  10),

('JP', NULL, 'TELL Lifeline (English)',
  '03-5774-0992', NULL,
  'https://telljp.com',
  '9am-11pm daily',
  ARRAY['English'],
  ARRAY['general_distress','mental_health_crisis'],
  'English-language support in Japan.',
  10),

('JP', NULL, 'Yorisoi Hotline',
  '0120-279-338', NULL,
  'https://www.since2011.net',
  '24/7',
  ARRAY['Japanese'],
  ARRAY['general_distress','mental_health_crisis','suicide'],
  'Free national hotline in Japanese.',
  20),

('BR', NULL, 'CVV (Centro de Valorização da Vida)',
  '188', NULL,
  'https://www.cvv.org.br',
  '24/7',
  ARRAY['Portuguese'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Free emotional support and suicide prevention across Brazil.',
  10),

('MX', NULL, 'SAPTEL',
  '55 5259 8121', NULL,
  'http://www.saptel.org.mx',
  '24/7',
  ARRAY['Spanish'],
  ARRAY['general_distress','mental_health_crisis','suicide'],
  'Free crisis support and counselling.',
  10),

('AR', NULL, 'Centro de Asistencia al Suicida',
  '135', NULL,
  'https://www.asistenciaalsuicida.org.ar',
  '24/7',
  ARRAY['Spanish'],
  ARRAY['suicide','mental_health_crisis'],
  'Free national suicide prevention line.',
  10),

-- ── International fallback (always shown) ─────────────────────
('INTL', NULL, 'Befrienders Worldwide',
  NULL, NULL,
  'https://befrienders.org',
  'Varies by country',
  ARRAY['Multiple'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Find a crisis helpline in your country. Network covering 32+ countries with emotional support volunteers.',
  10),

('INTL', NULL, 'Find a Helpline',
  NULL, NULL,
  'https://findahelpline.com',
  'Varies by country',
  ARRAY['Multiple'],
  ARRAY['general_distress','suicide','mental_health_crisis'],
  'Searchable directory of free, confidential support hotlines and chat services in 130+ countries.',
  20),

('INTL', NULL, 'IASP Crisis Centre Directory',
  NULL, NULL,
  'https://www.iasp.info/resources/Crisis_Centres/',
  'Varies by country',
  ARRAY['Multiple'],
  ARRAY['suicide','mental_health_crisis'],
  'International Association for Suicide Prevention. Comprehensive global directory.',
  30);

-- Verify
SELECT country_code, COUNT(*) AS resource_count
FROM crisis_resources
GROUP BY country_code
ORDER BY country_code;
